# Generated by Django 3.0.4 on 2020-04-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapout_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
