# Generated by Django 3.0.5 on 2020-04-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapout_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='Leave some words to decribe youself.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Hidden', max_length=6),
        ),
    ]
