# Generated by Django 3.0.4 on 2020-04-20 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapout_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_modify',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Event Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
