# Generated by Django 3.0.4 on 2020-04-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapout_app', '0002_tasks_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='belong_project',
        ),
        migrations.CreateModel(
            name='Budgetplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belong_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapout_app.Project')),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='belong_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mapout_app.Budgetplan'),
            preserve_default=False,
        ),
    ]
