# Generated by Django 3.0.4 on 2020-04-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapout_app', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='usertable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=16)),
            ],
        ),
    ]
