# Generated by Django 3.0.4 on 2020-04-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapout_app', '0002_auto_20200417_2126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='project',
        ),
    ]
