# Generated by Django 3.0.4 on 2020-04-23 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapout_app', '0003_anouncement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anouncement',
            new_name='Announcement',
        ),
    ]
