# Generated by Django 3.0.4 on 2020-04-17 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapout_app', '0004_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Project_description',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Project_name',
            new_name='project_name',
        ),
        migrations.AddField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(related_name='member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ManyToManyField(related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField()),
                ('due_date', models.DateField(verbose_name='Event Date')),
                ('finish', models.BooleanField(default=False)),
                ('belong_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapout_app.Project')),
                ('incharge', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
