# Generated by Django 3.0.5 on 2020-04-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapout_app', '0006_auto_20200423_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
