# Generated by Django 3.0.4 on 2020-04-18 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapout_app', '0011_auto_20200418_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='title',
            new_name='filename',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=1, upload_to='files'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='belong_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapout_app.Project'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='belong_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapout_app.Project'),
        ),
    ]
