# Generated by Django 3.0.5 on 2020-04-20 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mapout_app', '0022_auto_20200420_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Privacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='belong_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapout_app.Project'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='belong_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapout_app.Project'),
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
