# Generated by Django 3.0.5 on 2020-04-21 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapout_app', '0027_merge_20200421_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('transition_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='belong_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapout_app.Project'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='belong_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapout_app.Project'),
        ),
    ]
