# Generated by Django 3.0.5 on 2020-04-21 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapout_app', '0028_auto_20200421_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='belong_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapout_app.Project'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='belong_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapout_app.Project'),
        ),
    ]
